{% set version = "7.6.4.1" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/refs/tags/v{{ version }}-beta.tar.gz
  sha256: 9396e070aebbfb07386ed8074a3573b8137f11bd31f11c08bbe40a5e1ae6e9b2
  patches:
    - intel-mac.patch  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman
  run:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman
    - pyqt

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - josborne-noaa
    - karlmattsmith
    - ocefpaf
