{% set version = "7.4.3" %}

package:
  name: pyferret
  version: {{ version }}

source:
  fn: pyferret-{{ version }}.tar.gz
  url: https://github.com/NOAA-PMEL/PyFerret/archive/{{ version }}.tar.gz
  sha256: 27442cc6baceb0a0b3c583c1622cd6f62a96c3fc8666a882c60d2c80f932ffbf
  patches:
    - intel-mac.patch  # [osx]

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
    - netcdf-fortran
    - cairo
    - pango
    - pixman
  run:
    - python
    - numpy
    - netcdf-fortran
    - cairo
    - pango
    - pixman
    - pyqt

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
