{% set version = "7.0.1" %}
{% set commit = "26cd0bc5e3d8b4ee9f3272abc0d18fecbc373d6f" %}

package:
  name: pyferret
  version: {{ version }}.dev

source:
  fn: pyferret-{{ version }}.tar.gz
  url: https://github.com/NOAA-PMEL/PyFerret/archive/{{ commit }}.tar.gz
  sha256: 4e6c97f0442f2d12b915fc469018b1df8193bb310d3b825c6178b6bac06093d6
  patches:
    - site_specific.patch  # [not win]
    - linux-platform_specific.patch  # [linux]
    - osx-platform_specific.patch  # [osx]

build:
  number: 6
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - numpy
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.40.*
    - pixman 0.34.*
    - gcc  # [not win]
  run:
    - python
    - numpy
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.40.*
    - pixman 0.34.*
    - pyqt 4.11.*
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - pyferret
  commands:
    - conda inspect linkages -p $PREFIX pyferret  # [not win]
    - conda inspect objects -p $PREFIX pyferret  # [osx]

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
