travis:
  secure:
    BINSTAR_TOKEN: nQZDC2joSsa/gydDktxwGYRNMwX+bOZpuzmqgpIMM0pXEE+T3MncFNKHmNtdeoCwx1/zKBr1UuQIxfH0B2hnSqNgX588TeH0KzPZfDpdiWDtiN3mV+W9Gl46+EppMsVzrWq2Fp/U8nsOkv6vLTOo5qBGx3uHTr/+o95Go36DUGiDIIFgRSR7giN5ylOU/RvRy0d00aGH7p9j6ww9R23d7pWHSCFHoTtCD827EwJlmRg5hoGAIiNPd6EMsX9r4xTiL2k3B/AI5XZ9ByRyNyk1xwi6jxSO2IJXdAGXquMezLqa9wNPHKSR8c2k88oJH932cobUVAyutfMCAWoqc3U4S5gyVJjUp3dLRkb6zw8pW6ra+bDBdq22sj1EJw5DseFvieNaqzuKJKxLVI0sIe4fdvCNXmMTgjgmKVRK5zod4+SyRT+zEmiNj5Z26F73Wtbm7cK4ZLxUZxGZikE0QUPgb5Lse8LqZBFjfP0qM5Vff+Cz+yhphoYjjE/7kgQPInaZNQZZLQ2FZRX/n436Q96cxzcvHmezl1GiGcVZ+U3pUMDM8b/CENgxE3fN6DxaiIjA7GQ+UwtqoM5ndNidWbg9nUeDSeFE7Xh26xfJ8KUu1vK1cUME06uZgqTQ7KUUgio++TeWnRGOFCbcvSorsDU9LomtSx+0SK2lpynp0Hy9MVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
