travis:
  secure:
    BINSTAR_TOKEN: B4oC8Qw/Gt1a5ni4P8ZdCrEj3qlUKqkzC4m0jY3qWUvx979aidEyvnrz9EDWHaRSsie85JcU51nmdLDPDh5ZTy1wA3i627rP4BBZ4t8c2aC2V3S6c1RBYVrG8QjsY1+9vFdy3guYsIkkRx9zwa7DxG+tqSzRF8cHcQu82OOfMr4G3rpfhqHk7LBqo/35L7u2+Ertxa99r0XLqsiX8IRP1bLaxnpqBaAaCAH0wFd/3nPKLl4Hfbb/o5qhtdrvKE+BFWXUcZCWtQg64gHo6oZhTyZRGHmDMCKt230Ylo1Yz6O5hjThFfNkuVV/DDXek94qi/+vOtN6OgdGziYxZKBIpcbOvbrGdeyB3TWSJyC+sR3UvsSCy8Glk+m54u5bYG39avRhzEu2V94z7p1MpMaKZtgmD9cxbiSikRGyGggcgdHjE/Y97GGSM7ldI+DzMpzOMskxvkQcM+ozEjrj5Rd2wK0EjNaN5CJjv3MXzzd8UhI1hPr4w8Sk3dvUi3CreSSHcFdGI32wvVuzKk9GThAVMwDuN8gduBB2awyCNW71qlyK3z/dUTqSusHe1FerotP7NRDgv2t3uAtRq0J4KFAB4XqrWsQ3qEw8MIbtAiMs0rngEeTMkA61UWSL99fZzc3KTAUmLXoIizt8GPNVk2lFIAu+HpERMOnGwjVhEugjAHU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
